import logging
from typing import List
from fastapi import Depends, status
from sqlalchemy.orm import Session
from app.models import post
from app.schema import schemas
from fastapi import APIRouter
from app.db.database import get_db
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix='/posts',
    tags=['Posts']
)


@router.get('/', response_model=List[schemas.CreatePost])
def test_posts(db: Session = Depends(get_db)):
    results = db.query(post.Post).all()

    return results


@router.post('/', status_code=status.HTTP_201_CREATED,
             response_model=schemas.CreatePost)
async def create_posts(
        post_create: schemas.CreatePost,
        db: AsyncSession = Depends(get_db)  # Change type to AsyncSession
):
    # 1. Convert Pydantic model to SQLAlchemy model
    # Note: .dict() is deprecated in Pydantic v2; use .model_dump()
    new_post = post.Post(**post_create.model_dump())

    # 2. Add to the session (this part is still sync in memory)
    db.add(new_post)

    # 3. COMMIT must be awaited
    await db.commit()

    # 4. REFRESH must be awaited to get the ID generated by the DB
    await db.refresh(new_post)

    logger.debug(f"Successfully created post with ID: {new_post.id}")

    return new_post
